# https://docs.travis-ci.com/user/languages/go
language: go

go:
  - 1.6

before_install:
  - go get golang.org/x/lint/golint
# - go get github.com/mattn/goveralls

matrix:
  fast_finish: true

script: 
  - go vet -x ./...
  - $HOME/gopath/bin/golint ./...
  - go test -v ./...
# - go test -covermode=count -coverprofile=profile.cov .

#after_script:
# - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci